In [1]:
import pandas as pd

In [2]:
import requests

url = "https://zillow56.p.rapidapi.com/search_polygon"

querystring = {"polygon":"34.03959576441558 -118.50636536779786,34.0418716916327 -118.50276047888184,34.042440663894304 -118.49846894445801,34.04201393505594 -118.49417741003418,34.04087598099002 -118.4897142142334,34.03945351693672 -118.48525101843262,34.03788877892429 -118.48095948400879,34.03618175908096 -118.47683961096192,34.034190192514366 -118.47271973791504,34.031629538228394 -118.46962983312989,34.02835747861639 -118.4677415579834,34.02465847668084 -118.46671158972168,34.02081703478521 -118.46636826696778,34.01697541902413 -118.46636826696778,34.01341821237762 -118.4673982352295,34.011283816847104 -118.47100312414551,34.01057233974687 -118.47563798132325,34.01043004361143 -118.47992951574707,34.01071463564384 -118.48439271154786,34.01156840601794 -118.48868424597168,34.01270675316253 -118.49297578039551,34.01398737545716 -118.49709565344239,34.01555255425154 -118.50104386511231,34.01754455825562 -118.50464875402832,34.02039019717532 -118.50756699743653,34.02352028980117 -118.50962693395996,34.02707707311613 -118.51065690222168,34.03063370735633 -118.50997025671387,34.034190192514366 -118.5091119498291,34.03774652858273 -118.50825364294434,34.03959576441558 -118.50636536779786","output":"json","status":"forSale","sortSelection":"priorityscore","listing_type":"by_agent","doz":"any"}

headers = {
	"x-rapidapi-key": "333241ee78mshb1f03dfddfa879cp12d4f0jsn16a3cc6e99ae",
	"x-rapidapi-host": "zillow56.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'results': [{'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/9ac0d58bd947990e98a7c6feddc32060-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.025856, 'listing_sub_type': {'is_FSBA': True, 'is_openHouse': True}, 'livingArea': 1004.0, 'longitude': -118.501976, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7483.608, 'openHouse': 'Sat. 2-4pm', 'open_house_info': {'open_house_showing': [{'open_house_end': 1760223600000, 'open_house_start': 1760216400000}, {'open_house_end': 1760313600000, 'open_house_start': 1760302800000}]}, 'price': 1165000.0, 'priceForHDP': 1165000.0, 'rentZestimate': 4490, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '817 6th St APT A', 'taxAssessedValue': 964245.0, 'timeOnZillow': 115211000, 'unit': 'Apt A', 'zestimate': 1157100, 'zipcode': '90403', 'zpid': 20484992}, {'bathrooms': 4.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1759215600000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'MULTI_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/c6843720f4bebc52801ff6fdece15ed9-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.034615, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1469.0, 'longitude': -118.48012, 'lotAreaUnit': 'sqft', 'lotAreaValue': 6211.656, 'price': 1199000.0, 'priceChange': -150000, 'priceForHDP': 1199000.0, 'priceReduction': '$150,000 (Sep 30)', 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1147 24th St #A-B', 'timeOnZillow': 6332639000, 'unit': '# A-B', 'zestimate': 1234900, 'zipcode': '90403', 'zpid': 455351929}, {'bathrooms': 3.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/cfc9a51e88f475eb8339bcdcb49dab43-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.017593, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1418.0, 'longitude': -118.48273, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7514.0, 'price': 990000.0, 'priceForHDP': 990000.0, 'rentZestimate': 4918, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1754 11th St UNIT 101', 'taxAssessedValue': 391903.0, 'timeOnZillow': 284210000, 'unit': 'Unit 101', 'zestimate': 1005000, 'zipcode': '90404', 'zpid': 20479916}, {'bathrooms': 15.0, 'bedrooms': 11.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/fa16ff881b0352aa744bad0da9c936fb-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.0192, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 9899.0, 'longitude': -118.505844, 'lotAreaUnit': 'sqft', 'lotAreaValue': 5505.984, 'price': 38500000.0, 'priceForHDP': 38500000.0, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '938-940 Palisades Beach Rd', 'timeOnZillow': 1001423000, 'zipcode': '90403', 'zpid': 456957893}, {'bathrooms': 1.0, 'bedrooms': 1.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1755327600000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/0ab3516293ce9fa2c72e5acecfb6a505-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02828, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 440.0, 'longitude': -118.49284, 'lotAreaUnit': 'sqft', 'lotAreaValue': 1319.868, 'price': 999000.0, 'priceChange': -101000, 'priceForHDP': 999000.0, 'priceReduction': '$101,000 (Aug 16)', 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1012 1/2 Euclid St', 'taxAssessedValue': 913190.0, 'timeOnZillow': 17922338000, 'zipcode': '90403', 'zpid': 20478685}, {'bathrooms': 1.0, 'bedrooms': 1.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1756364400000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/379ba2c7ab01cefcfd37b14e2bc5cde8-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.020752, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1043.0, 'longitude': -118.50077, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.6892791551882461, 'price': 599100.0, 'priceChange': -40800, 'priceForHDP': 599100.0, 'priceReduction': '$40,800 (Aug 28)', 'rentZestimate': 4503, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1040 4th St #112', 'taxAssessedValue': 634173.0, 'timeOnZillow': 131439410000, 'unit': '# 112', 'zipcode': '90403', 'zpid': 20485330}, {'bathrooms': 6.0, 'bedrooms': 4.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/3cbebb772f87fa1e60b32a4072e6f2e4-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.01903, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 5030.0, 'longitude': -118.50577, 'lotAreaUnit': 'sqft', 'lotAreaValue': 5536.476, 'price': 19500000.0, 'priceForHDP': 19500000.0, 'rentZestimate': 5702, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '940 Palisades Beach Rd', 'taxAssessedValue': 3959878.0, 'timeOnZillow': 1001423000, 'zestimate': 18681200, 'zipcode': '90403', 'zpid': 20485846}, {'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1756882800000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/ca026d0c07e1a36cfd5bf28f6dc994ba-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02569, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 918.0, 'longitude': -118.501, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7483.608, 'price': 899000.0, 'priceChange': -30000, 'priceForHDP': 899000.0, 'priceReduction': '$30,000 (Sep 3)', 'rentZestimate': 4221, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '844 7th St APT 1', 'taxAssessedValue': 393971.0, 'timeOnZillow': 9899414000, 'unit': 'Apt 1', 'zestimate': 903700, 'zipcode': '90403', 'zpid': 20484960}, {'bathrooms': 1.0, 'bedrooms': 1.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1750316400000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/08b9533ab23c1b4c70048324e8396623-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02662, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 722.0, 'longitude': -118.47892, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.3446, 'price': 499000.0, 'priceChange': -51000, 'priceForHDP': 499000.0, 'priceReduction': '', 'rentZestimate': 2931, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1912 Broadway APT 107', 'taxAssessedValue': 396594.0, 'timeOnZillow': 12120882000, 'unit': 'Apt 107', 'zipcode': '90404', 'zpid': 92426247}, {'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/3b06e5e0488deefa29c54c646138d377-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02153, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1355.0, 'longitude': -118.5035, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.3446, 'price': 1149000.0, 'priceForHDP': 1149000.0, 'rentZestimate': 5402, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '930 3rd St APT 307', 'taxAssessedValue': 1250469.0, 'timeOnZillow': 6080657000, 'unit': 'Apt 307', 'zestimate': 1150800, 'zipcode': '90403', 'zpid': 20485470}, {'bathrooms': 6.0, 'bedrooms': 6.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1750230000000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/8221c459d7209f84c2873d0bc6c1210a-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.03766, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 5900.0, 'longitude': -118.50507, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.2881, 'price': 8995000.0, 'priceChange': -454000, 'priceForHDP': 8995000.0, 'priceReduction': '', 'rentZestimate': 28257, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1202 San Vicente Blvd', 'taxAssessedValue': 4584595.0, 'timeOnZillow': 13354751000, 'zipcode': '90402', 'zpid': 20477450}, {'bathrooms': 3.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/6568e5c8d02ed024670101238ed99590-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.024708, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1865.0, 'longitude': -118.51018, 'lotAreaUnit': 'acres', 'lotAreaValue': 1.5479, 'price': 2649000.0, 'priceForHDP': 2649000.0, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '515 Ocean Ave UNIT 502N', 'timeOnZillow': 2445326000, 'unit': 'Unit 502N', 'zipcode': '90402', 'zpid': 456559605}, {'bathrooms': 4.0, 'bedrooms': 6.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1758870000000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/990c03a3a764ff219370730760d0802b-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.03985, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 3103.0, 'longitude': -118.50098, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7527.168, 'price': 3995000.0, 'priceChange': 45000, 'priceForHDP': 3995000.0, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '212 16th St', 'taxAssessedValue': 286706.0, 'timeOnZillow': 4529628000, 'zipcode': '90402', 'zpid': 20477160}, {'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1757055600000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/77e1c5f102c9809df8452a3552bb6117-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.025658, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2000.0, 'longitude': -118.50825, 'lotAreaUnit': 'sqft', 'lotAreaValue': 10624.284, 'price': 5395000.0, 'priceChange': -100000, 'priceForHDP': 5395000.0, 'priceReduction': '$100,000 (Sep 5)', 'rentZestimate': 4919, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '227 Alta Ave', 'taxAssessedValue': 3163774.0, 'timeOnZillow': 2718797000, 'zestimate': 5296100, 'zipcode': '90402', 'zpid': 20486265}, {'bathrooms': 3.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1756364400000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/521d94e157f6515eafa98cde3d7329a4-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.033016, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1803.0, 'longitude': -118.47912, 'lotAreaUnit': 'sqft', 'lotAreaValue': 5318.676, 'price': 1360000.0, 'priceChange': -30000, 'priceForHDP': 1360000.0, 'priceReduction': '$30,000 (Aug 28)', 'rentZestimate': 6633, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1240 24th St UNIT 3', 'taxAssessedValue': 1456414.0, 'timeOnZillow': 6951843000, 'unit': 'Unit 3', 'zestimate': 1354400, 'zipcode': '90404', 'zpid': 20474535}, {'bathrooms': 3.0, 'bedrooms': 6.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/7dedc9fefc17595800163e0a1cafdafb-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.016705, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2751.0, 'longitude': -118.47945, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7497.0, 'price': 1950000.0, 'priceForHDP': 1950000.0, 'rentZestimate': 5535, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1836 Euclid St', 'taxAssessedValue': 1250567.0, 'timeOnZillow': 716210000, 'zestimate': 1930900, 'zipcode': '90404', 'zpid': 20480089}, {'bathrooms': 4.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/5e1918eb31e27195c58ccfd65c4db5b5-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.030945, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1850.0, 'longitude': -118.4895, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7505.388, 'price': 1795000.0, 'priceForHDP': 1795000.0, 'rentZestimate': 7588, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1013 16th St UNIT 101', 'taxAssessedValue': 1210486.0, 'timeOnZillow': 6503423000, 'unit': 'Unit 101', 'zestimate': 1780000, 'zipcode': '90403', 'zpid': 20478100}, {'bathrooms': 3.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1759474800000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/511e1956dde315869615a5a7301828db-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.033455, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2142.0, 'longitude': -118.49165, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7505.388, 'price': 2595000.0, 'priceChange': -100000, 'priceForHDP': 2595000.0, 'priceReduction': '$100,000 (Oct 3)', 'rentZestimate': 8328, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '838 17th St APT 105', 'taxAssessedValue': 2236860.0, 'timeOnZillow': 975846000, 'unit': 'Apt 105', 'zestimate': 2549100, 'zipcode': '90403', 'zpid': 51582400}, {'bathrooms': 4.0, 'bedrooms': 5.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/7350ec6dd16ce7ccea394a0c38ff3ec0-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.039165, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 3250.0, 'longitude': -118.50202, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7496.676, 'price': 5195000.0, 'priceForHDP': 5195000.0, 'rentZestimate': 17855, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '210 15th St', 'taxAssessedValue': 3865800.0, 'timeOnZillow': 970158000, 'zestimate': 5193300, 'zipcode': '90402', 'zpid': 20477206}, {'bathrooms': 4.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/1b7dd78269c362b18695c71a49b83701-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.027794, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2580.0, 'longitude': -118.49793, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7527.168, 'price': 2395000.0, 'priceForHDP': 2395000.0, 'rentZestimate': 7674, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '852 10th St APT 1', 'taxAssessedValue': 2043593.0, 'timeOnZillow': 307458000, 'unit': 'Apt 1', 'zestimate': 2377600, 'zipcode': '90403', 'zpid': 102961436}, {'bathrooms': 3.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/3f69cc5669d280665b44daac091b0ff4-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.032608, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1588.0, 'longitude': -118.48961, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.34450000000000003, 'price': 1625000.0, 'priceForHDP': 1625000.0, 'rentZestimate': 6779, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '933 17th St UNIT 14', 'taxAssessedValue': 1485834.0, 'timeOnZillow': 5299736000, 'unit': 'Unit 14', 'zestimate': 1607500, 'zipcode': '90403', 'zpid': 20475069}, {'bathrooms': 8.0, 'bedrooms': 6.0, 'city': 'Santa Monica', 

In [3]:
data=response.json()

In [4]:
data

{'results': [{'bathrooms': 2.0,
   'bedrooms': 2.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'CONDO',
   'imgSrc': 'https://photos.zillowstatic.com/fp/9ac0d58bd947990e98a7c6feddc32060-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.025856,
   'listing_sub_type': {'is_FSBA': True, 'is_openHouse': True},
   'livingArea': 1004.0,
   'longitude': -118.501976,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7483.608,
   'openHouse': 'Sat. 2-4pm',
   'open_house_info': {'open_house_showing': [{'open_house_end': 1760223600000,
      'open_house_start': 1760216400000},
     {'open_house_end': 1760313600000, 'open_house_start': 1760302800000}]},
   'price': 1165000.0,
   'priceForHDP': 1165000.0,
   'rentZestimate': 4490,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '817 6th St APT A',
   'taxAssessedValue': 964245.0,
   'timeOnZillow': 115211000,
   'unit': 'Apt A',
   'zestimate': 1157100,
   'zipcode': '90403',
   'zpid': 20484992},
  {'bathrooms': 4.0,
   'bedrooms': 3.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1759215600000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'MULTI_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/c6843720f4bebc52801ff6fdece15ed9-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.034615,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 1469.0,
   'longitude': -118.48012,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 6211.656,
   'price': 1199000.0,
   'priceChange': -150000,
   'priceForHDP': 1199000.0,
   'priceReduction': '$150,000 (Sep 30)',
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1147 24th St #A-B',
   'timeOnZillow': 6332639000,
   'unit': '# A-B',
   'zestimate': 1234900,
   'zipcode': '90403',
   'zpid': 455351929},
  {'bathrooms': 3.0,
   'bedrooms': 2.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'CONDO',
   'imgSrc': 'https://photos.zillowstatic.com/fp/cfc9a51e88f475eb8339bcdcb49dab43-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.017593,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 1418.0,
   'longitude': -118.48273,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7514.0,
   'price': 990000.0,
   'priceForHDP': 990000.0,
   'rentZestimate': 4918,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1754 11th St UNIT 101',
   'taxAssessedValue': 391903.0,
   'timeOnZillow': 284210000,
   'unit': 'Unit 101',
   'zestimate': 1005000,
   'zipcode': '90404',
   'zpid': 20479916},
  {'bathrooms': 15.0,
   'bedrooms': 11.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/fa16ff881b0352aa744bad0da9c936fb-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.0192,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 9899.0,
   'longitude': -118.505844,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 5505.984,
   'price': 38500000.0,
   'priceForHDP': 38500000.0,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '938-940 Palisades Beach Rd',
   'timeOnZillow': 1001423000,
   'zipcode': '90403',
   'zpid': 456957893},
  {'bathrooms': 1.0,
   'bedrooms': 1.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1755327600000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/0ab3516293ce9fa2c72e5acecfb6a505-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.02828,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 440.0,
   'longitude': -118.49284,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 1319.868,
   'price': 999000.0,
   'priceChange': -101000,
   'priceForHDP': 999000.0,
   'priceReduction': '$101,000 (Aug 16)',
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1012 1/2 Euclid St',
   'taxAssessedValue': 913190.0,
   'timeOnZillow': 17922338000,
   'zipcode': '90403',
   'zpid': 20478685},
  {'bathrooms': 1.0,
   'bedrooms': 1.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1756364400000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'CONDO',
   'imgSrc': 'https://photos.zillowstatic.com/fp/379ba2c7ab01cefcfd37b14e2bc5cde8-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.020752,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 1043.0,
   'longitude': -118.50077,
   'lotAreaUnit': 'acres',
   'lotAreaValue': 0.6892791551882461,
   'price': 599100.0,
   'priceChange': -40800,
   'priceForHDP': 599100.0,
   'priceReduction': '$40,800 (Aug 28)',
   'rentZestimate': 4503,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1040 4th St #112',
   'taxAssessedValue': 634173.0,
   'timeOnZillow': 131439410000,
   'unit': '# 112',
   'zipcode': '90403',
   'zpid': 20485330},
  {'bathrooms': 6.0,
   'bedrooms': 4.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/3cbebb772f87fa1e60b32a4072e6f2e4-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.01903,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 5030.0,
   'longitude': -118.50577,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 5536.476,
   'price': 19500000.0,
   'priceForHDP': 19500000.0,
   'rentZestimate': 5702,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '940 Palisades Beach Rd',
   'taxAssessedValue': 3959878.0,
   'timeOnZillow': 1001423000,
   'zestimate': 18681200,
   'zipcode': '90403',
   'zpid': 20485846},
  {'bathrooms': 2.0,
   'bedrooms': 2.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1756882800000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'CONDO',
   'imgSrc': 'https://photos.zillowstatic.com/fp/ca026d0c07e1a36cfd5bf28f6dc994ba-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.02569,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 918.0,
   'longitude': -118.501,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7483.608,
   'price': 899000.0,
   'priceChange': -30000,
   'priceForHDP': 899000.0,
   'priceReduction': '$30,000 (Sep 3)',
   'rentZestimate': 4221,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '844 7th St APT 1',
   'taxAssessedValue': 393971.0,
   'timeOnZillow': 9899414000,
   'unit': 'Apt 1',
   'zestimate': 903700,
   'zipcode': '90403',
   'zpid': 20484960},
  {'bathrooms': 1.0,
   'bedrooms': 1.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1750316400000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'CONDO',
   'imgSrc': 'https://photos.zillowstatic.com/fp/08b9533ab23c1b4c70048324e8396623-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.02662,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 722.0,
   'longitude': -118.47892,
   'lotAreaUnit': 'acres',
   'lotAreaValue': 0.3446,
   'price': 499000.0,
   'priceChange': -51000,
   'priceForHDP': 499000.0,
   'priceReduction': '',
   'rentZestimate': 2931,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1912 Broadway APT 107',
   'taxAssessedValue': 396594.0,
   'timeOnZillow': 12120882000,
   'unit': 'Apt 107',
   'zipcode': '90404',
   'zpid': 92426247},
  {'bathrooms': 2.0,
   'bedrooms': 2.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'CONDO',
   'imgSrc': 'https://photos.zillowstatic.com/fp/3b06e5e0488deefa29c54c646138d377-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.02153,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 1355.0,
   'longitude': -118.5035,
   'lotAreaUnit': 'acres',
   'lotAreaValue': 0.3446,
   'price': 1149000.0,
   'priceForHDP': 1149000.0,
   'rentZestimate': 5402,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '930 3rd St APT 307',
   'taxAssessedValue': 1250469.0,
   'timeOnZillow': 6080657000,
   'unit': 'Apt 307',
   'zestimate': 1150800,
   'zipcode': '90403',
   'zpid': 20485470},
  {'bathrooms': 6.0,
   'bedrooms': 6.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1750230000000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/8221c459d7209f84c2873d0bc6c1210a-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.03766,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 5900.0,
   'longitude': -118.50507,
   'lotAreaUnit': 'acres',
   'lotAreaValue': 0.2881,
   'price': 8995000.0,
   'priceChange': -454000,
   'priceForHDP': 8995000.0,
   'priceReduction': '',
   'rentZestimate': 28257,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1202 San Vicente Blvd',
   'taxAssessedValue': 4584595.0,
   'timeOnZillow': 13354751000,
   'zipcode': '90402',
   'zpid': 20477450},
  {'bathrooms': 3.0,
   'bedrooms': 2.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'CONDO',
   'imgSrc': 'https://photos.zillowstatic.com/fp/6568e5c8d02ed024670101238ed99590-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.024708,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 1865.0,
   'longitude': -118.51018,
   'lotAreaUnit': 'acres',
   'lotAreaValue': 1.5479,
   'price': 2649000.0,
   'priceForHDP': 2649000.0,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '515 Ocean Ave UNIT 502N',
   'timeOnZillow': 2445326000,
   'unit': 'Unit 502N',
   'zipcode': '90402',
   'zpid': 456559605},
  {'bathrooms': 4.0,
   'bedrooms': 6.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1758870000000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/990c03a3a764ff219370730760d0802b-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.03985,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 3103.0,
   'longitude': -118.50098,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7527.168,
   'price': 3995000.0,
   'priceChange': 45000,
   'priceForHDP': 3995000.0,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '212 16th St',
   'taxAssessedValue': 286706.0,
   'timeOnZillow': 4529628000,
   'zipcode': '90402',
   'zpid': 20477160},
  {'bathrooms': 2.0,
   'bedrooms': 2.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1757055600000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/77e1c5f102c9809df8452a3552bb6117-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.025658,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 2000.0,
   'longitude': -118.50825,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 10624.284,
   'price': 5395000.0,
   'priceChange': -100000,
   'priceForHDP': 5395000.0,
   'priceReduction': '$100,000 (Sep 5)',
   'rentZestimate': 4919,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '227 Alta Ave',
   'taxAssessedValue': 3163774.0,
   'timeOnZillow': 2718797000,
   'zestimate': 5296100,
   'zipcode': '90402',
   'zpid': 20486265},
  {'bathrooms': 3.0,
   'bedrooms': 3.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1756364400000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'TOWNHOUSE',
   'imgSrc': 'https://photos.zillowstatic.com/fp/521d94e157f6515eafa98cde3d7329a4-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.033016,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 1803.0,
   'longitude': -118.47912,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 5318.676,
   'price': 1360000.0,
   'priceChange': -30000,
   'priceForHDP': 1360000.0,
   'priceReduction': '$30,000 (Aug 28)',
   'rentZestimate': 6633,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1240 24th St UNIT 3',
   'taxAssessedValue': 1456414.0,
   'timeOnZillow': 6951843000,
   'unit': 'Unit 3',
   'zestimate': 1354400,
   'zipcode': '90404',
   'zpid': 20474535},
  {'bathrooms': 3.0,
   'bedrooms': 6.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/7dedc9fefc17595800163e0a1cafdafb-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.016705,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 2751.0,
   'longitude': -118.47945,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7497.0,
   'price': 1950000.0,
   'priceForHDP': 1950000.0,
   'rentZestimate': 5535,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1836 Euclid St',
   'taxAssessedValue': 1250567.0,
   'timeOnZillow': 716210000,
   'zestimate': 1930900,
   'zipcode': '90404',
   'zpid': 20480089},
  {'bathrooms': 4.0,
   'bedrooms': 3.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'TOWNHOUSE',
   'imgSrc': 'https://photos.zillowstatic.com/fp/5e1918eb31e27195c58ccfd65c4db5b5-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.030945,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 1850.0,
   'longitude': -118.4895,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7505.388,
   'price': 1795000.0,
   'priceForHDP': 1795000.0,
   'rentZestimate': 7588,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '1013 16th St UNIT 101',
   'taxAssessedValue': 1210486.0,
   'timeOnZillow': 6503423000,
   'unit': 'Unit 101',
   'zestimate': 1780000,
   'zipcode': '90403',
   'zpid': 20478100},
  {'bathrooms': 3.0,
   'bedrooms': 3.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'datePriceChanged': 1759474800000,
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'TOWNHOUSE',
   'imgSrc': 'https://photos.zillowstatic.com/fp/511e1956dde315869615a5a7301828db-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.033455,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 2142.0,
   'longitude': -118.49165,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7505.388,
   'price': 2595000.0,
   'priceChange': -100000,
   'priceForHDP': 2595000.0,
   'priceReduction': '$100,000 (Oct 3)',
   'rentZestimate': 8328,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '838 17th St APT 105',
   'taxAssessedValue': 2236860.0,
   'timeOnZillow': 975846000,
   'unit': 'Apt 105',
   'zestimate': 2549100,
   'zipcode': '90403',
   'zpid': 51582400},
  {'bathrooms': 4.0,
   'bedrooms': 5.0,
   'city': 'Santa Monica',
   'country': 'USA',
   'currency': 'USD',
   'daysOnZillow': -1,
   'homeStatus': 'FOR_SALE',
   'homeStatusForHDP': 'FOR_SALE',
   'homeType': 'SINGLE_FAMILY',
   'imgSrc': 'https://photos.zillowstatic.com/fp/7350ec6dd16ce7ccea394a0c38ff3ec0-p_e.jpg',
   'isFeatured': False,
   'isNonOwnerOccupied': True,
   'isPreforeclosureAuction': False,
   'isPremierBuilder': False,
   'isShowcaseListing': False,
   'isUnmappable': False,
   'isZillowOwned': False,
   'latitude': 34.039165,
   'listing_sub_type': {'is_FSBA': True},
   'livingArea': 3250.0,
   'longitude': -118.50202,
   'lotAreaUnit': 'sqft',
   'lotAreaValue': 7496.676,
   'price': 5195000.0,
   'priceForHDP': 5195000.0,
   'rentZestimate': 17855,
   'shouldHighlight': False,
   'state': 'CA',
   'streetAddress': '210 15th St',

In [5]:
data.keys()

dict_keys(['results', 'resultsPerPage', 'totalPages', 'totalResultCount'])

In [6]:
data.values()

dict_values([[{'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/9ac0d58bd947990e98a7c6feddc32060-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.025856, 'listing_sub_type': {'is_FSBA': True, 'is_openHouse': True}, 'livingArea': 1004.0, 'longitude': -118.501976, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7483.608, 'openHouse': 'Sat. 2-4pm', 'open_house_info': {'open_house_showing': [{'open_house_end': 1760223600000, 'open_house_start': 1760216400000}, {'open_house_end': 1760313600000, 'open_house_start': 1760302800000}]}, 'price': 1165000.0, 'priceForHDP': 1165000.0, 'rentZestimate': 4490, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '817 6th St APT A', 'taxAssessedValue': 964245.0, 'timeOnZillow': 115211000, 'unit': 'Apt A', 'zestimate': 1157100, 'zipcode': '90403', 'zpid': 20484992}, {'bathrooms': 4.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1759215600000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'MULTI_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/c6843720f4bebc52801ff6fdece15ed9-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.034615, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1469.0, 'longitude': -118.48012, 'lotAreaUnit': 'sqft', 'lotAreaValue': 6211.656, 'price': 1199000.0, 'priceChange': -150000, 'priceForHDP': 1199000.0, 'priceReduction': '$150,000 (Sep 30)', 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1147 24th St #A-B', 'timeOnZillow': 6332639000, 'unit': '# A-B', 'zestimate': 1234900, 'zipcode': '90403', 'zpid': 455351929}, {'bathrooms': 3.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/cfc9a51e88f475eb8339bcdcb49dab43-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.017593, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1418.0, 'longitude': -118.48273, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7514.0, 'price': 990000.0, 'priceForHDP': 990000.0, 'rentZestimate': 4918, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1754 11th St UNIT 101', 'taxAssessedValue': 391903.0, 'timeOnZillow': 284210000, 'unit': 'Unit 101', 'zestimate': 1005000, 'zipcode': '90404', 'zpid': 20479916}, {'bathrooms': 15.0, 'bedrooms': 11.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/fa16ff881b0352aa744bad0da9c936fb-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.0192, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 9899.0, 'longitude': -118.505844, 'lotAreaUnit': 'sqft', 'lotAreaValue': 5505.984, 'price': 38500000.0, 'priceForHDP': 38500000.0, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '938-940 Palisades Beach Rd', 'timeOnZillow': 1001423000, 'zipcode': '90403', 'zpid': 456957893}, {'bathrooms': 1.0, 'bedrooms': 1.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1755327600000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/0ab3516293ce9fa2c72e5acecfb6a505-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02828, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 440.0, 'longitude': -118.49284, 'lotAreaUnit': 'sqft', 'lotAreaValue': 1319.868, 'price': 999000.0, 'priceChange': -101000, 'priceForHDP': 999000.0, 'priceReduction': '$101,000 (Aug 16)', 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1012 1/2 Euclid St', 'taxAssessedValue': 913190.0, 'timeOnZillow': 17922338000, 'zipcode': '90403', 'zpid': 20478685}, {'bathrooms': 1.0, 'bedrooms': 1.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1756364400000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/379ba2c7ab01cefcfd37b14e2bc5cde8-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.020752, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1043.0, 'longitude': -118.50077, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.6892791551882461, 'price': 599100.0, 'priceChange': -40800, 'priceForHDP': 599100.0, 'priceReduction': '$40,800 (Aug 28)', 'rentZestimate': 4503, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1040 4th St #112', 'taxAssessedValue': 634173.0, 'timeOnZillow': 131439410000, 'unit': '# 112', 'zipcode': '90403', 'zpid': 20485330}, {'bathrooms': 6.0, 'bedrooms': 4.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/3cbebb772f87fa1e60b32a4072e6f2e4-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.01903, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 5030.0, 'longitude': -118.50577, 'lotAreaUnit': 'sqft', 'lotAreaValue': 5536.476, 'price': 19500000.0, 'priceForHDP': 19500000.0, 'rentZestimate': 5702, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '940 Palisades Beach Rd', 'taxAssessedValue': 3959878.0, 'timeOnZillow': 1001423000, 'zestimate': 18681200, 'zipcode': '90403', 'zpid': 20485846}, {'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1756882800000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/ca026d0c07e1a36cfd5bf28f6dc994ba-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02569, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 918.0, 'longitude': -118.501, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7483.608, 'price': 899000.0, 'priceChange': -30000, 'priceForHDP': 899000.0, 'priceReduction': '$30,000 (Sep 3)', 'rentZestimate': 4221, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '844 7th St APT 1', 'taxAssessedValue': 393971.0, 'timeOnZillow': 9899414000, 'unit': 'Apt 1', 'zestimate': 903700, 'zipcode': '90403', 'zpid': 20484960}, {'bathrooms': 1.0, 'bedrooms': 1.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1750316400000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/08b9533ab23c1b4c70048324e8396623-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02662, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 722.0, 'longitude': -118.47892, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.3446, 'price': 499000.0, 'priceChange': -51000, 'priceForHDP': 499000.0, 'priceReduction': '', 'rentZestimate': 2931, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1912 Broadway APT 107', 'taxAssessedValue': 396594.0, 'timeOnZillow': 12120882000, 'unit': 'Apt 107', 'zipcode': '90404', 'zpid': 92426247}, {'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/3b06e5e0488deefa29c54c646138d377-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.02153, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1355.0, 'longitude': -118.5035, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.3446, 'price': 1149000.0, 'priceForHDP': 1149000.0, 'rentZestimate': 5402, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '930 3rd St APT 307', 'taxAssessedValue': 1250469.0, 'timeOnZillow': 6080657000, 'unit': 'Apt 307', 'zestimate': 1150800, 'zipcode': '90403', 'zpid': 20485470}, {'bathrooms': 6.0, 'bedrooms': 6.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1750230000000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/8221c459d7209f84c2873d0bc6c1210a-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.03766, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 5900.0, 'longitude': -118.50507, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.2881, 'price': 8995000.0, 'priceChange': -454000, 'priceForHDP': 8995000.0, 'priceReduction': '', 'rentZestimate': 28257, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1202 San Vicente Blvd', 'taxAssessedValue': 4584595.0, 'timeOnZillow': 13354751000, 'zipcode': '90402', 'zpid': 20477450}, {'bathrooms': 3.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/6568e5c8d02ed024670101238ed99590-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.024708, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1865.0, 'longitude': -118.51018, 'lotAreaUnit': 'acres', 'lotAreaValue': 1.5479, 'price': 2649000.0, 'priceForHDP': 2649000.0, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '515 Ocean Ave UNIT 502N', 'timeOnZillow': 2445326000, 'unit': 'Unit 502N', 'zipcode': '90402', 'zpid': 456559605}, {'bathrooms': 4.0, 'bedrooms': 6.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1758870000000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/990c03a3a764ff219370730760d0802b-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.03985, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 3103.0, 'longitude': -118.50098, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7527.168, 'price': 3995000.0, 'priceChange': 45000, 'priceForHDP': 3995000.0, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '212 16th St', 'taxAssessedValue': 286706.0, 'timeOnZillow': 4529628000, 'zipcode': '90402', 'zpid': 20477160}, {'bathrooms': 2.0, 'bedrooms': 2.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1757055600000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/77e1c5f102c9809df8452a3552bb6117-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.025658, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2000.0, 'longitude': -118.50825, 'lotAreaUnit': 'sqft', 'lotAreaValue': 10624.284, 'price': 5395000.0, 'priceChange': -100000, 'priceForHDP': 5395000.0, 'priceReduction': '$100,000 (Sep 5)', 'rentZestimate': 4919, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '227 Alta Ave', 'taxAssessedValue': 3163774.0, 'timeOnZillow': 2718797000, 'zestimate': 5296100, 'zipcode': '90402', 'zpid': 20486265}, {'bathrooms': 3.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1756364400000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/521d94e157f6515eafa98cde3d7329a4-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.033016, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1803.0, 'longitude': -118.47912, 'lotAreaUnit': 'sqft', 'lotAreaValue': 5318.676, 'price': 1360000.0, 'priceChange': -30000, 'priceForHDP': 1360000.0, 'priceReduction': '$30,000 (Aug 28)', 'rentZestimate': 6633, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1240 24th St UNIT 3', 'taxAssessedValue': 1456414.0, 'timeOnZillow': 6951843000, 'unit': 'Unit 3', 'zestimate': 1354400, 'zipcode': '90404', 'zpid': 20474535}, {'bathrooms': 3.0, 'bedrooms': 6.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/7dedc9fefc17595800163e0a1cafdafb-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.016705, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2751.0, 'longitude': -118.47945, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7497.0, 'price': 1950000.0, 'priceForHDP': 1950000.0, 'rentZestimate': 5535, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1836 Euclid St', 'taxAssessedValue': 1250567.0, 'timeOnZillow': 716210000, 'zestimate': 1930900, 'zipcode': '90404', 'zpid': 20480089}, {'bathrooms': 4.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/5e1918eb31e27195c58ccfd65c4db5b5-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.030945, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1850.0, 'longitude': -118.4895, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7505.388, 'price': 1795000.0, 'priceForHDP': 1795000.0, 'rentZestimate': 7588, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '1013 16th St UNIT 101', 'taxAssessedValue': 1210486.0, 'timeOnZillow': 6503423000, 'unit': 'Unit 101', 'zestimate': 1780000, 'zipcode': '90403', 'zpid': 20478100}, {'bathrooms': 3.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'datePriceChanged': 1759474800000, 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/511e1956dde315869615a5a7301828db-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.033455, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2142.0, 'longitude': -118.49165, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7505.388, 'price': 2595000.0, 'priceChange': -100000, 'priceForHDP': 2595000.0, 'priceReduction': '$100,000 (Oct 3)', 'rentZestimate': 8328, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '838 17th St APT 105', 'taxAssessedValue': 2236860.0, 'timeOnZillow': 975846000, 'unit': 'Apt 105', 'zestimate': 2549100, 'zipcode': '90403', 'zpid': 51582400}, {'bathrooms': 4.0, 'bedrooms': 5.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'SINGLE_FAMILY', 'imgSrc': 'https://photos.zillowstatic.com/fp/7350ec6dd16ce7ccea394a0c38ff3ec0-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.039165, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 3250.0, 'longitude': -118.50202, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7496.676, 'price': 5195000.0, 'priceForHDP': 5195000.0, 'rentZestimate': 17855, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '210 15th St', 'taxAssessedValue': 3865800.0, 'timeOnZillow': 970158000, 'zestimate': 5193300, 'zipcode': '90402', 'zpid': 20477206}, {'bathrooms': 4.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'CONDO', 'imgSrc': 'https://photos.zillowstatic.com/fp/1b7dd78269c362b18695c71a49b83701-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.027794, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 2580.0, 'longitude': -118.49793, 'lotAreaUnit': 'sqft', 'lotAreaValue': 7527.168, 'price': 2395000.0, 'priceForHDP': 2395000.0, 'rentZestimate': 7674, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '852 10th St APT 1', 'taxAssessedValue': 2043593.0, 'timeOnZillow': 307458000, 'unit': 'Apt 1', 'zestimate': 2377600, 'zipcode': '90403', 'zpid': 102961436}, {'bathrooms': 3.0, 'bedrooms': 3.0, 'city': 'Santa Monica', 'country': 'USA', 'currency': 'USD', 'daysOnZillow': -1, 'homeStatus': 'FOR_SALE', 'homeStatusForHDP': 'FOR_SALE', 'homeType': 'TOWNHOUSE', 'imgSrc': 'https://photos.zillowstatic.com/fp/3f69cc5669d280665b44daac091b0ff4-p_e.jpg', 'isFeatured': False, 'isNonOwnerOccupied': True, 'isPreforeclosureAuction': False, 'isPremierBuilder': False, 'isShowcaseListing': False, 'isUnmappable': False, 'isZillowOwned': False, 'latitude': 34.032608, 'listing_sub_type': {'is_FSBA': True}, 'livingArea': 1588.0, 'longitude': -118.48961, 'lotAreaUnit': 'acres', 'lotAreaValue': 0.34450000000000003, 'price': 1625000.0, 'priceForHDP': 1625000.0, 'rentZestimate': 6779, 'shouldHighlight': False, 'state': 'CA', 'streetAddress': '933 17th St UNIT 14', 'taxAssessedValue': 1485834.0, 'timeOnZillow': 5299736000, 'unit': 'Unit 14', 'zestimate': 1607500, 'zipcode': '90403', 'zpid': 20475069}, {'bathrooms': 8.0, 'bedrooms': 6.0, 'city': 'Santa Monica',

In [13]:
data['results']

[{'bathrooms': 2.0,
  'bedrooms': 2.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/9ac0d58bd947990e98a7c6feddc32060-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.025856,
  'listing_sub_type': {'is_FSBA': True, 'is_openHouse': True},
  'livingArea': 1004.0,
  'longitude': -118.501976,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7483.608,
  'openHouse': 'Sat. 2-4pm',
  'open_house_info': {'open_house_showing': [{'open_house_end': 1760223600000,
     'open_house_start': 1760216400000},
    {'open_house_end': 1760313600000, 'open_house_start': 1760302800000}]},
  'price': 1165000.0,
  'priceForHDP': 1165000.0,
  'rentZestimate': 4490,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '817 6th St APT A',
  'taxAssessedValue': 964245.0,
  'timeOnZillow': 115211000,
  'unit': 'Apt A',
  'zestimate': 1157100,
  'zipcode': '90403',
  'zpid': 20484992},
 {'bathrooms': 4.0,
  'bedrooms': 3.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1759215600000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'MULTI_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/c6843720f4bebc52801ff6fdece15ed9-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.034615,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 1469.0,
  'longitude': -118.48012,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 6211.656,
  'price': 1199000.0,
  'priceChange': -150000,
  'priceForHDP': 1199000.0,
  'priceReduction': '$150,000 (Sep 30)',
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1147 24th St #A-B',
  'timeOnZillow': 6332639000,
  'unit': '# A-B',
  'zestimate': 1234900,
  'zipcode': '90403',
  'zpid': 455351929},
 {'bathrooms': 3.0,
  'bedrooms': 2.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/cfc9a51e88f475eb8339bcdcb49dab43-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.017593,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 1418.0,
  'longitude': -118.48273,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7514.0,
  'price': 990000.0,
  'priceForHDP': 990000.0,
  'rentZestimate': 4918,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1754 11th St UNIT 101',
  'taxAssessedValue': 391903.0,
  'timeOnZillow': 284210000,
  'unit': 'Unit 101',
  'zestimate': 1005000,
  'zipcode': '90404',
  'zpid': 20479916},
 {'bathrooms': 15.0,
  'bedrooms': 11.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/fa16ff881b0352aa744bad0da9c936fb-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.0192,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 9899.0,
  'longitude': -118.505844,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 5505.984,
  'price': 38500000.0,
  'priceForHDP': 38500000.0,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '938-940 Palisades Beach Rd',
  'timeOnZillow': 1001423000,
  'zipcode': '90403',
  'zpid': 456957893},
 {'bathrooms': 1.0,
  'bedrooms': 1.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1755327600000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/0ab3516293ce9fa2c72e5acecfb6a505-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.02828,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 440.0,
  'longitude': -118.49284,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 1319.868,
  'price': 999000.0,
  'priceChange': -101000,
  'priceForHDP': 999000.0,
  'priceReduction': '$101,000 (Aug 16)',
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1012 1/2 Euclid St',
  'taxAssessedValue': 913190.0,
  'timeOnZillow': 17922338000,
  'zipcode': '90403',
  'zpid': 20478685},
 {'bathrooms': 1.0,
  'bedrooms': 1.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1756364400000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/379ba2c7ab01cefcfd37b14e2bc5cde8-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.020752,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 1043.0,
  'longitude': -118.50077,
  'lotAreaUnit': 'acres',
  'lotAreaValue': 0.6892791551882461,
  'price': 599100.0,
  'priceChange': -40800,
  'priceForHDP': 599100.0,
  'priceReduction': '$40,800 (Aug 28)',
  'rentZestimate': 4503,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1040 4th St #112',
  'taxAssessedValue': 634173.0,
  'timeOnZillow': 131439410000,
  'unit': '# 112',
  'zipcode': '90403',
  'zpid': 20485330},
 {'bathrooms': 6.0,
  'bedrooms': 4.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/3cbebb772f87fa1e60b32a4072e6f2e4-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.01903,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 5030.0,
  'longitude': -118.50577,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 5536.476,
  'price': 19500000.0,
  'priceForHDP': 19500000.0,
  'rentZestimate': 5702,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '940 Palisades Beach Rd',
  'taxAssessedValue': 3959878.0,
  'timeOnZillow': 1001423000,
  'zestimate': 18681200,
  'zipcode': '90403',
  'zpid': 20485846},
 {'bathrooms': 2.0,
  'bedrooms': 2.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1756882800000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/ca026d0c07e1a36cfd5bf28f6dc994ba-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.02569,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 918.0,
  'longitude': -118.501,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7483.608,
  'price': 899000.0,
  'priceChange': -30000,
  'priceForHDP': 899000.0,
  'priceReduction': '$30,000 (Sep 3)',
  'rentZestimate': 4221,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '844 7th St APT 1',
  'taxAssessedValue': 393971.0,
  'timeOnZillow': 9899414000,
  'unit': 'Apt 1',
  'zestimate': 903700,
  'zipcode': '90403',
  'zpid': 20484960},
 {'bathrooms': 1.0,
  'bedrooms': 1.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1750316400000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/08b9533ab23c1b4c70048324e8396623-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.02662,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 722.0,
  'longitude': -118.47892,
  'lotAreaUnit': 'acres',
  'lotAreaValue': 0.3446,
  'price': 499000.0,
  'priceChange': -51000,
  'priceForHDP': 499000.0,
  'priceReduction': '',
  'rentZestimate': 2931,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1912 Broadway APT 107',
  'taxAssessedValue': 396594.0,
  'timeOnZillow': 12120882000,
  'unit': 'Apt 107',
  'zipcode': '90404',
  'zpid': 92426247},
 {'bathrooms': 2.0,
  'bedrooms': 2.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/3b06e5e0488deefa29c54c646138d377-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.02153,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 1355.0,
  'longitude': -118.5035,
  'lotAreaUnit': 'acres',
  'lotAreaValue': 0.3446,
  'price': 1149000.0,
  'priceForHDP': 1149000.0,
  'rentZestimate': 5402,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '930 3rd St APT 307',
  'taxAssessedValue': 1250469.0,
  'timeOnZillow': 6080657000,
  'unit': 'Apt 307',
  'zestimate': 1150800,
  'zipcode': '90403',
  'zpid': 20485470},
 {'bathrooms': 6.0,
  'bedrooms': 6.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1750230000000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/8221c459d7209f84c2873d0bc6c1210a-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.03766,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 5900.0,
  'longitude': -118.50507,
  'lotAreaUnit': 'acres',
  'lotAreaValue': 0.2881,
  'price': 8995000.0,
  'priceChange': -454000,
  'priceForHDP': 8995000.0,
  'priceReduction': '',
  'rentZestimate': 28257,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1202 San Vicente Blvd',
  'taxAssessedValue': 4584595.0,
  'timeOnZillow': 13354751000,
  'zipcode': '90402',
  'zpid': 20477450},
 {'bathrooms': 3.0,
  'bedrooms': 2.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/6568e5c8d02ed024670101238ed99590-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.024708,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 1865.0,
  'longitude': -118.51018,
  'lotAreaUnit': 'acres',
  'lotAreaValue': 1.5479,
  'price': 2649000.0,
  'priceForHDP': 2649000.0,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '515 Ocean Ave UNIT 502N',
  'timeOnZillow': 2445326000,
  'unit': 'Unit 502N',
  'zipcode': '90402',
  'zpid': 456559605},
 {'bathrooms': 4.0,
  'bedrooms': 6.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1758870000000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/990c03a3a764ff219370730760d0802b-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.03985,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 3103.0,
  'longitude': -118.50098,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7527.168,
  'price': 3995000.0,
  'priceChange': 45000,
  'priceForHDP': 3995000.0,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '212 16th St',
  'taxAssessedValue': 286706.0,
  'timeOnZillow': 4529628000,
  'zipcode': '90402',
  'zpid': 20477160},
 {'bathrooms': 2.0,
  'bedrooms': 2.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1757055600000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/77e1c5f102c9809df8452a3552bb6117-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.025658,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 2000.0,
  'longitude': -118.50825,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 10624.284,
  'price': 5395000.0,
  'priceChange': -100000,
  'priceForHDP': 5395000.0,
  'priceReduction': '$100,000 (Sep 5)',
  'rentZestimate': 4919,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '227 Alta Ave',
  'taxAssessedValue': 3163774.0,
  'timeOnZillow': 2718797000,
  'zestimate': 5296100,
  'zipcode': '90402',
  'zpid': 20486265},
 {'bathrooms': 3.0,
  'bedrooms': 3.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1756364400000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'TOWNHOUSE',
  'imgSrc': 'https://photos.zillowstatic.com/fp/521d94e157f6515eafa98cde3d7329a4-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.033016,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 1803.0,
  'longitude': -118.47912,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 5318.676,
  'price': 1360000.0,
  'priceChange': -30000,
  'priceForHDP': 1360000.0,
  'priceReduction': '$30,000 (Aug 28)',
  'rentZestimate': 6633,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1240 24th St UNIT 3',
  'taxAssessedValue': 1456414.0,
  'timeOnZillow': 6951843000,
  'unit': 'Unit 3',
  'zestimate': 1354400,
  'zipcode': '90404',
  'zpid': 20474535},
 {'bathrooms': 3.0,
  'bedrooms': 6.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/7dedc9fefc17595800163e0a1cafdafb-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.016705,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 2751.0,
  'longitude': -118.47945,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7497.0,
  'price': 1950000.0,
  'priceForHDP': 1950000.0,
  'rentZestimate': 5535,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1836 Euclid St',
  'taxAssessedValue': 1250567.0,
  'timeOnZillow': 716210000,
  'zestimate': 1930900,
  'zipcode': '90404',
  'zpid': 20480089},
 {'bathrooms': 4.0,
  'bedrooms': 3.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'TOWNHOUSE',
  'imgSrc': 'https://photos.zillowstatic.com/fp/5e1918eb31e27195c58ccfd65c4db5b5-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.030945,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 1850.0,
  'longitude': -118.4895,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7505.388,
  'price': 1795000.0,
  'priceForHDP': 1795000.0,
  'rentZestimate': 7588,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '1013 16th St UNIT 101',
  'taxAssessedValue': 1210486.0,
  'timeOnZillow': 6503423000,
  'unit': 'Unit 101',
  'zestimate': 1780000,
  'zipcode': '90403',
  'zpid': 20478100},
 {'bathrooms': 3.0,
  'bedrooms': 3.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'datePriceChanged': 1759474800000,
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'TOWNHOUSE',
  'imgSrc': 'https://photos.zillowstatic.com/fp/511e1956dde315869615a5a7301828db-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.033455,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 2142.0,
  'longitude': -118.49165,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7505.388,
  'price': 2595000.0,
  'priceChange': -100000,
  'priceForHDP': 2595000.0,
  'priceReduction': '$100,000 (Oct 3)',
  'rentZestimate': 8328,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '838 17th St APT 105',
  'taxAssessedValue': 2236860.0,
  'timeOnZillow': 975846000,
  'unit': 'Apt 105',
  'zestimate': 2549100,
  'zipcode': '90403',
  'zpid': 51582400},
 {'bathrooms': 4.0,
  'bedrooms': 5.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'SINGLE_FAMILY',
  'imgSrc': 'https://photos.zillowstatic.com/fp/7350ec6dd16ce7ccea394a0c38ff3ec0-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.039165,
  'listing_sub_type': {'is_FSBA': True},
  'livingArea': 3250.0,
  'longitude': -118.50202,
  'lotAreaUnit': 'sqft',
  'lotAreaValue': 7496.676,
  'price': 5195000.0,
  'priceForHDP': 5195000.0,
  'rentZestimate': 17855,
  'shouldHighlight': False,
  'state': 'CA',
  'streetAddress': '210 15th St',
  'taxAssessedValue': 3865800.0,
  'timeOnZillow': 970158000,
  'zestimate': 5193300,
  'zipcode': '90402',
  'zpid': 20477206},
 {'bathrooms': 4.0,
  'bedrooms': 3.0,
  'city': 'Santa Monica',
  'country': 'USA',
  'currency': 'USD',
  'daysOnZillow': -1,
  'homeStatus': 'FOR_SALE',
  'homeStatusForHDP': 'FOR_SALE',
  'homeType': 'CONDO',
  'imgSrc': 'https://photos.zillowstatic.com/fp/1b7dd78269c362b18695c71a49b83701-p_e.jpg',
  'isFeatured': False,
  'isNonOwnerOccupied': True,
  'isPreforeclosureAuction': False,
  'isPremierBuilder': False,
  'isShowcaseListing': False,
  'isUnmappable': False,
  'isZillowOwned': False,
  'latitude': 34.027794,
  'listing_sub_type': {'is_FSBA': True},

In [21]:
a=pd.json_normalize(data['results'])

In [22]:
a

,bathrooms,bedrooms,city,country,currency,daysOnZillow,homeStatus,homeStatusForHDP,homeType,imgSrc,...,zipcode,zpid,listing_sub_type.is_FSBA,listing_sub_type.is_openHouse,open_house_info.open_house_showing,datePriceChanged,priceChange,priceReduction,newConstructionType,listing_sub_type.is_newHome
0,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/9ac0d58bd94...,...,90403,20484992,True,True,"[{'open_house_end': 1760223600000, 'open_house...",NaN,NaN,NaN,NaN,NaN
1,4.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,MULTI_FAMILY,https://photos.zillowstatic.com/fp/c6843720f4b...,...,90403,455351929,True,NaN,NaN,1.759216e+12,-150000.0,"$150,000 (Sep 30)",NaN,NaN
2,3.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/cfc9a51e88f...,...,90404,20479916,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15.0,11.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/fa16ff881b0...,...,90403,456957893,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/0ab3516293c...,...,90403,20478685,True,NaN,NaN,1.755328e+12,-101000.0,"$101,000 (Aug 16)",NaN,NaN
5,1.0,1.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/379ba2c7ab0...,...,90403,20485330,True,NaN,NaN,1.756364e+12,-40800.0,"$40,800 (Aug 28)",NaN,NaN
6,6.0,4.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/3cbebb772f8...,...,90403,20485846,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/ca026d0c07e...,...,90403,20484960,True,NaN,NaN,1.756883e+12,-30000.0,"$30,000 (Sep 3)",NaN,NaN
8,1.0,1.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/08b9533ab23...,...,90404,92426247,True,NaN,NaN,1.750316e+12,-51000.0,,NaN,NaN
9,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/3b06e5e0488...,...,90403,20485470,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,6.0,6.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/8221c459d72...,...,90402,20477450,True,NaN,NaN,1.750230e+12,-454000.0,,NaN,NaN
11,3.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/6568e5c8d02...,...,90402,456559605,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,4.0,6.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/990c03a3a76...,...,90402,20477160,True,NaN,NaN,1.758870e+12,45000.0,NaN,NaN,NaN
13,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/77e1c5f102c...,...,90402,20486265,True,NaN,NaN,1.757056e+12,-100000.0,"$100,000 (Sep 5)",NaN,NaN
14,3.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/521d94e157f...,...,90404,20474535,True,NaN,NaN,1.756364e+12,-30000.0,"$30,000 (Aug 28)",NaN,NaN
15,3.0,6.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/7dedc9fefc1...,...,90404,20480089,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,4.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/5e1918eb31e...,...,90403,20478100,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/511e1956dde...,...,90403,51582400,True,NaN,NaN,1.759475e+12,-100000.0,"$100,000 (Oct 3)",NaN,NaN
18,4.0,5.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/7350ec6dd16...,...,90402,20477206,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,4.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/1b7dd78269c...,...,90403,102961436,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,3.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/3f69cc5669d...,...,90403,20475069,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,8.0,6.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/f063974b84b...,...,90402,20486488,NaN,NaN,NaN,NaN,NaN,NaN,BUILDER_SPEC,True
22,6.0,5.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/c914d925d44...,...,90402,20476240,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,4.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/297c6fe4158...,...,90402,20486251,True,NaN,NaN,1.758524e+12,-224000.0,"$224,000 (Sep 22)",NaN,NaN
24,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/26787ea10e3...,...,90403,20475159,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/85b39c939bd...,...,90403,20478617,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,7.0,6.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/f962f4612e3...,...,90402,20477746,NaN,NaN,NaN,NaN,NaN,NaN,BUILDER_SPEC,True
27,3.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/2bb2e280c1f...,...,90404,20473885,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/adf94cc6b6d...,...,90405,20484049,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,3.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/5ddc945798f...,...,90404,20474614,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,38.0,38.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,MULTI_FAMILY,https://photos.zillowstatic.com/fp/f84ebebd6a1...,...,90403,2068792684,True,NaN,NaN,1.756796e+12,-2000000.0,"$2,000,000 (Sep 2)",NaN,NaN
31,4.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/799da9e2c3f...,...,90403,20478314,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,8.0,7.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/bf15b12e5f0...,...,90402,20476410,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/dd91f2355f4...,...,90402,20477297,True,True,"[{'open_house_end': 1759870800000, 'open_house...",NaN,NaN,NaN,NaN,NaN
34,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/2a09adcdd68...,...,90403,20474861,True,True,"[{'open_house_end': 1760641200000, 'open_house...",1.759129e+12,-50000.0,"$50,000 (Sep 29)",NaN,NaN
35,3.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/a32dadfc7b1...,...,90403,20485537,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/9c6fbb26017...,...,90403,20475571,True,NaN,NaN,1.757401e+12,-40000.0,"$40,000 (Sep 9)",NaN,NaN
37,1.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/96c92b05844...,...,90401,20484693,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,5.0,4.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/bc7b9cf2f39...,...,90402,20539643,True,NaN,NaN,1.752908e+12,-449000.0,"$449,000 (Jul 19)",NaN,NaN
39,3.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,TOWNHOUSE,https://photos.zillowstatic.com/fp/0e18d02c859...,...,90403,55198014,True,NaN,NaN,1.759475e+12,-151000.0,"$151,000 (Oct 3)",NaN,NaN
40,3.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/69c1e7b08aa...,...,90403,2098895547,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
a.to_csv('home.csv')

In [24]:
a.head()

,bathrooms,bedrooms,city,country,currency,daysOnZillow,homeStatus,homeStatusForHDP,homeType,imgSrc,...,zipcode,zpid,listing_sub_type.is_FSBA,listing_sub_type.is_openHouse,open_house_info.open_house_showing,datePriceChanged,priceChange,priceReduction,newConstructionType,listing_sub_type.is_newHome
0,2.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/9ac0d58bd94...,...,90403,20484992,True,True,"[{'open_house_end': 1760223600000, 'open_house...",NaN,NaN,NaN,NaN,NaN
1,4.0,3.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,MULTI_FAMILY,https://photos.zillowstatic.com/fp/c6843720f4b...,...,90403,455351929,True,NaN,NaN,1.759216e+12,-150000.0,"$150,000 (Sep 30)",NaN,NaN
2,3.0,2.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,CONDO,https://photos.zillowstatic.com/fp/cfc9a51e88f...,...,90404,20479916,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15.0,11.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/fa16ff881b0...,...,90403,456957893,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,Santa Monica,USA,USD,-1,FOR_SALE,FOR_SALE,SINGLE_FAMILY,https://photos.zillowstatic.com/fp/0ab3516293c...,...,90403,20478685,True,NaN,NaN,1.755328e+12,-101000.0,"$101,000 (Aug 16)",NaN,NaN