In [1]:
import pandas as pd

## 1. Opening a local csv

In [67]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv')

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.9,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0

## 2. Opening csv file from url

In [ ]:
csv_url = "https://cdn.wsform.com/wp-content/uploads/2020/06/color_web_safe.csv" 
pd.read_csv(csv_url)

## sep parameter

In [22]:
csv_url2='https://support.staffbase.com/hc/en-us/article_attachments/360009197091/email-password-recovery-code.csv'

In [23]:
pd.read_csv(csv_url2)

  Login email;Identifier;One-time password;Recovery code;First name;Last name;Department;Location
0  rachel@example.com;9012;12se74;rb9012;Rachel;B...
1  laura@example.com;2070;04ap67;lg2070;Laura;Gre...
2  craig@example.com;4081;30no86;cj4081;Craig;Joh...
3  mary@example.com;9346;14ju73;mj9346;Mary;Jenki...
4  jamie@example.com;5079;09ja61;js5079;Jamie;Smi...

In [24]:
pd.read_csv(csv_url2,sep=';')

,Login email,Identifier,One-time password,Recovery code,First name,Last name,Department,Location
0,rachel@example.com,9012,12se74,rb9012,Rachel,Booker,Sales,Manchester
1,laura@example.com,2070,04ap67,lg2070,Laura,Grey,Depot,London
2,craig@example.com,4081,30no86,cj4081,Craig,Johnson,Depot,London
3,mary@example.com,9346,14ju73,mj9346,Mary,Jenkins,Engineering,Manchester
4,jamie@example.com,5079,09ja61,js5079,Jamie,Smith,Engineering,Manchester

## 4. columns has no headings

In [ ]:
# if some columns has no headings then they can be named at importing time itself

pd.read_csv(csv_url2,names=['1st col','2nd col','3rd col'],sep=';')

## 5. index column parameter

In [28]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/train.csv')

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [29]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/train.csv',index_col='id')

,title,author,text,label
id,,,,
0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...
20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

## 6. header parameter

In [33]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/gld_price_data.csv',header=1)

# ignore example, i am just avoiding importing multiple datasets to avoid mess

       1/2/2008  1447.160034   84.860001  78.470001    15.18  1.471692
0      1/3/2008  1447.160034   85.570000  78.370003  15.2850  1.474491
1      1/4/2008  1411.630005   85.129997  77.309998  15.1670  1.475492
2      1/7/2008  1416.180054   84.769997  75.500000  15.0530  1.468299
3      1/8/2008  1390.189941   86.779999  76.059998  15.5900  1.557099
4      1/9/2008  1409.130005   86.550003  75.250000  15.5200  1.466405
...         ...          ...         ...        ...      ...       ...
2284   5/8/2018  2671.919922  124.589996  14.060000  15.5100  1.186789
2285   5/9/2018  2697.790039  124.330002  14.370000  15.5300  1.184722
2286  5/10/2018  2723.070068  125.180000  14.410000  15.7400  1.191753
2287  5/14/2018  2730.129883  124.489998  14.380000  15.5600  1.193118
2288  5/16/2018  2725.780029  122.543800  14.405800  15.4542  1.182033

[2289 rows x 6 columns]

## 7. usecols parameter

In [34]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/train.csv',usecols=['title','text'])

,title,text
0,House Dem Aide: We Didn’t Even See Comey’s Let...,House Dem Aide: We Didn’t Even See Comey’s Let...
1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Ever get the feeling your life circles the rou...
2,Why the Truth Might Get You Fired,"Why the Truth Might Get You Fired October 29, ..."
3,15 Civilians Killed In Single US Airstrike Hav...,Videos 15 Civilians Killed In Single US Airstr...
4,Iranian woman jailed for fictional unpublished...,Print \nAn Iranian woman has been sentenced to...
...,...,...
20795,Rapper T.I.: Trump a ’Poster Child For White S...,Rapper T. I. unloaded on black celebrities who...
20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",When the Green Bay Packers lost to the Washing...
20797,Macy’s Is Said to Receive Takeover Approach by...,The Macy’s of today grew from the union of sev...
20798,"NATO, Russia To Hold Parallel Exercises In Bal...","NATO, Russia To Hold Parallel Exercises In Bal..."
20799,What Keeps the F-35 Alive,"David Swanson is an author, activist, journa..."

## 8. squeeze parameter

In [53]:
df=pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/train.csv',usecols=['title'])

In [56]:
df.squeeze()

# read documentation for more

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799                            What Keeps the F-35 Alive
Name: title, Length: 20800, dtype: object

## 9. skip rows or nrows

In [57]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv', skiprows=[i for i in range(50) if i%5!=0])

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
1,Ford Figo Diesel Celebration Edition,2013,200000,169000,Diesel,Individual,Manual,First Owner,20.00,1399.0,68.1,5.0
2,Maruti Wagon R LXI Minor,2009,180000,90000,Petrol,Individual,Manual,Second Owner,18.90,1061.0,67,5.0
3,Hyundai i20 2015-2017 Asta 1.4 CRDi,2016,680000,100000,Diesel,Individual,Manual,First Owner,22.54,1396.0,88.73,5.0
4,Tata Tigor 2017-2020 XZ,2018,500000,35000,Petrol,Individual,Manual,First Owner,20.30,1199.0,83.81,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8083,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
8084,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110,5.0
8085,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.9,5.0
8086,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0
8087,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0

In [58]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv', nrows=100)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74.00,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90.00,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.20,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,525000,61500,Petrol,Dealer,Manual,First Owner,18.50,1197.0,82.85,5.0
96,Maruti Swift Dzire LDI,2016,600000,150000,Diesel,Individual,Manual,First Owner,26.59,1248.0,74.00,5.0
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,565000,72000,Petrol,Dealer,Automatic,First Owner,19.10,1197.0,82.00,5.0
98,Maruti Alto LX BSIII,2008,120000,68000,Petrol,Dealer,Manual,Third Owner,19.70,796.0,46.30,5.0
99,Hyundai i20 1.4 Asta Option,2017,725000,110000,Diesel,Individual,Manual,First Owner,22.54,1396.0,88.73,5.0

## 10. Encoding parameters

In [ ]:
pd.read_csv('some_example.csv',encoding='latin-1')

# by default most files are in utf-8. but if u find any new kind then we can use this

## 11. Skip bad lines 
#### if any rows has different num of columns

In [ ]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv', on_bad_lines='skip')
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv', on_bad_lines='warn')
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv', on_bad_lines='error')

## 12. dtype parameter

In [80]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv',dtype={'km_driven':float})

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500.0,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000.0,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000.0,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000.0,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000.0,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000.0,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000.0,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000.0,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.9,5.0
8126,Tata Indigo CR4,2013,290000,25000.0,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0
8127,Tata Indigo CR4,2013,290000,25000.0,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0

## 13. Handling Dates

In [82]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/gld_price_data.csv',parse_dates=['Date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2290 entries, 0 to 2289
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     2290 non-null   datetime64[ns]
 1   SPX      2290 non-null   float64
 2   GLD      2290 non-null   float64
 3   USO      2290 non-null   float64
 4   SLV      2290 non-null   float64
 5   EUR/USD  2290 non-null   float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 107.5 KB

## 14. Converters

In [84]:
def converter(name):
    if name=='First Owner':
        return 1
    elif name=='Second Owner':
        return 2
    elif name=='Third Owner	':
        return 3
    else:
        return 4

In [85]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv',converters={'owner':converter})

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,1,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,2,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,4,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,1,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,1,16.10,1298.0,88.2,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,1,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,4,16.80,1493.0,110,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,1,19.30,1248.0,73.9,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,1,23.57,1396.0,70,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,1,23.57,1396.0,70,5.0

## 15. na_values parameter

In [87]:
pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv', na_values=['First Owner'])

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,NaN,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,NaN,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,NaN,16.10,1298.0,88.2,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,NaN,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,NaN,19.30,1248.0,73.9,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,NaN,23.57,1396.0,70,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,NaN,23.57,1396.0,70,5.0

## 16. loading huge data chunks

In [88]:
df4=pd.read_csv('/Users/kishan/code/genai/ml/ml_learning/datasets/cardekho.csv',chunksize=2500)

In [89]:
for i in df4:
    print(i.shape)

(2500, 12)
(2500, 12)
(2500, 12)
(628, 12)