In [72]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [73]:
df=pd.read_csv('datasets/cardekho.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0

In [74]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## One Hot Encoding using Pandas

In [75]:
pd.get_dummies(df, columns=['owner','fuel']).head()

,name,year,selling_price,km_driven,seller_type,transmission,mileage(km/ltr/kg),engine,max_power,seats,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti Swift Dzire VDI,2014,450000,145500,Individual,Manual,23.40,1248.0,74,5.0,True,False,False,False,False,False,True,False,False
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Individual,Manual,21.14,1498.0,103.52,5.0,False,False,True,False,False,False,True,False,False
2,Honda City 2017-2020 EXi,2006,158000,140000,Individual,Manual,17.70,1497.0,78,5.0,False,False,False,False,True,False,False,False,True
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Individual,Manual,23.00,1396.0,90,5.0,True,False,False,False,False,False,True,False,False
4,Maruti Swift VXI BSIII,2007,130000,120000,Individual,Manual,16.10,1298.0,88.2,5.0,True,False,False,False,False,False,False,False,True

## K-1 One hot encoding using pandas
#### It helps to avoid multicolinearity issue

In [76]:
pd.get_dummies(df, columns=['owner'], drop_first=True).head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,mileage(km/ltr/kg),engine,max_power,seats,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,23.40,1248.0,74,5.0,False,False,False,False
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,21.14,1498.0,103.52,5.0,False,True,False,False
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,17.70,1497.0,78,5.0,False,False,False,True
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,23.00,1396.0,90,5.0,False,False,False,False
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,16.10,1298.0,88.2,5.0,False,False,False,False

## One Hot Encoding using Sklearn

In [77]:
from sklearn.preprocessing import OneHotEncoder

In [78]:
X = df[['name', 'km_driven', 'fuel']]
y = df['selling_price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [79]:
ohe= OneHotEncoder(drop='first', sparse_output=False)
X_train_encoded= ohe.fit_transform(X_train[['fuel']])
X_test_encoded= ohe.transform(X_test[['fuel']])

In [80]:
np.hstack((X_train[['name','km_driven']].values, X_train_encoded))

array([['Tata Tiago NRG Petrol AMT', 2560, 0.0, 0.0, 1.0],
       ['Honda Brio S MT', 80000, 0.0, 0.0, 1.0],
       ['Hyundai i20 1.4 CRDi Asta', 150000, 1.0, 0.0, 0.0],
       ...,
       ['Hyundai i20 Asta Option 1.2', 35000, 0.0, 0.0, 1.0],
       ['Maruti Swift Dzire VDI', 27000, 1.0, 0.0, 0.0],
       ['Maruti 800 AC', 70000, 0.0, 0.0, 1.0]],
      shape=(6502, 5), dtype=object)

In [81]:
np.hstack((X_train.values, X_train_encoded))

array([['Tata Tiago NRG Petrol AMT', 2560, 'Petrol', 0.0, 0.0, 1.0],
       ['Honda Brio S MT', 80000, 'Petrol', 0.0, 0.0, 1.0],
       ['Hyundai i20 1.4 CRDi Asta', 150000, 'Diesel', 1.0, 0.0, 0.0],
       ...,
       ['Hyundai i20 Asta Option 1.2', 35000, 'Petrol', 0.0, 0.0, 1.0],
       ['Maruti Swift Dzire VDI', 27000, 'Diesel', 1.0, 0.0, 0.0],
       ['Maruti 800 AC', 70000, 'Petrol', 0.0, 0.0, 1.0]],
      shape=(6502, 6), dtype=object)

## One Hot Encoding with Top Catogaries

In [82]:
df['name'].value_counts()

name
Maruti Swift Dzire VDI                             129
Maruti Alto 800 LXI                                 82
Maruti Alto LXi                                     71
BMW X4 M Sport X xDrive20d                          62
Maruti Swift VDI                                    61
                                                  ...
Skoda Fabia 1.4 TDI Ambiente                         1
Mahindra Scorpio VLX 2WD AT BSIII                    1
Renault KWID Climber 1.0 AMT                         1
Mahindra XUV300 W8 Option Dual Tone Diesel BSIV      1
Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV         1
Name: count, Length: 2058, dtype: int64

In [83]:
df['name'].nunique()
trishold=40
df['name']= np.where(df['name'].map(df['name'].value_counts())<trishold, 'other', df['name'])
df['name'].nunique()

15

In [84]:
df['name'].head(10)

0    Maruti Swift Dzire VDI
1                     other
2                     other
3                     other
4                     other
5                     other
6                     other
7                     other
8                     other
9                     other
Name: name, dtype: object

In [85]:
df['name'].value_counts()

name
other                                     7293
Maruti Swift Dzire VDI                     129
Maruti Alto 800 LXI                         82
Maruti Alto LXi                             71
BMW X4 M Sport X xDrive20d                  62
Maruti Swift VDI                            61
Maruti Swift VDI BSIV                       59
Maruti Wagon R LXI                          53
Maruti Alto K10 VXI                         50
Hyundai EON Era Plus                        48
Maruti Wagon R VXI BS IV                    45
Maruti Ertiga VDI                           45
Maruti Alto LX                              44
Toyota Innova 2.5 VX (Diesel) 7 Seater      44
Maruti Ritz VDi                             42
Name: count, dtype: int64